const nav=document.getElementById("nav"),menu=document.querySelector(".menu-toggle"),modal=document.getElementById("modal"),modalClose=document.getElementById("modalClose"),modalTitle=document.getElementById("modalTitle"),modalText=document.getElementById("modalText"),modalIcon=document.getElementById("modalIcon"),toast=document.getElementById("toast"),form=document.getElementById("demoForm");
menu.addEventListener("click",()=>nav.classList.toggle("open"));document.querySelectorAll(".nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
const roleCopy={provider:{icon:"🍱",title:"Become a Food Provider",text:"List your surplus food and help turn it into someone's next meal."},needer:{icon:"🔎",title:"Find Available Food",text:"Register to discover and request available food near you."},volunteer:{icon:"🚲",title:"Join as a Volunteer",text:"Help collect and deliver rescued food to where it is needed."}};
function openModal(role,food){const c=roleCopy[role]||roleCopy.needer;modalIcon.textContent=c.icon;modalTitle.textContent=food?"Request: "+food:c.title;modalText.textContent=c.text;modal.classList.add("show");document.body.style.overflow="hidden"}function closeModal(){modal.classList.remove("show");document.body.style.overflow=""}
document.querySelectorAll("[data-role]").forEach(el=>el.addEventListener("click",()=>openModal(el.dataset.role)));document.querySelectorAll(".request-btn").forEach(el=>el.addEventListener("click",()=>openModal("needer",el.dataset.food)));
modalClose.addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
form.addEventListener("submit",e=>{e.preventDefault();closeModal();toast.textContent="Thanks — your BachekoKhana request was received in demo mode.";toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3500);form.reset()});
const search=document.getElementById("foodSearch"),cards=[...document.querySelectorAll(".food-card")],filters=[...document.querySelectorAll(".filter")];let active="all";
function render(){const q=search.value.toLowerCase().trim();cards.forEach(card=>{const type=card.dataset.type,text=card.dataset.search,matchFilter=active==="all"||type.includes(active),matchSearch=!q||text.includes(q);card.style.display=matchFilter&&matchSearch?"":"none"})}
search.addEventListener("input",render);filters.forEach(btn=>btn.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));btn.classList.add("active");active=btn.dataset.filter;render()}));